### ISSUE TITLE
After a few Seconds Youtube says not enough Data

### ISSUE THREAD

**Issue by SNRSE** [gaborvecsei/RaspberryPi-Youtube-Live-Stream#10]
when i execute the script like you stated it runs fine for a few minutes and then it has a problem.
How can i check if this is a problem with the encoder or with the internet

**Comment by gaborvecsei** [comment]
Yes, this can be because of slow internet, or you are using an older HW which can not encode enough images, and this results in a bottleneck.

You can play with encoding settings here: https://github.com/gaborvecsei/YouTube-Live-Stream-Docker/blob/master/youtube_stream_image/code/simple_youtube_stream.sh#L8
